import React from 'react'
import Pixel from './Pixel'

const App = () => (
  <>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
    <Pixel></Pixel>
  </>

)

export default App
